[package]
name = "aera-vision-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
aera = { path = "../aera" }
anyhow = "1.0.90"
nalgebra = "0.33.1"
log = "0.4.22"
simple-log = "2.1.1"
rand = "0.8.5"
