[package]
name = "robot"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.213", features = ["derive"] }
serde-big-array = "0.5.1"
prost = "0.13.3"
anyhow = "1.0.90"