[package]
name = "pixy2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
cxx = "1.0"
opencv = { version = "0.93.3", features = ["clang-runtime"]}

[build-dependencies]
cxx-build = "1.0"
